### ISSUE TITLE
How to get data from response object 

### ISSUE THREAD

**Issue by 2007ay** [apigee-127/swagger-express#10]
Hi guy I am using swagger for my project, The problem what i am facing "unable to get data from the response object" Can some one help me to identified what i have done wrong below ?

```
var SwaggerExpress = require('swagger-express-mw');
var app = require('express')();

//this is done for schema validation
 var schemaValidator = require('./api/middlewares/schema_mw/schemaValidator');
 var validator = new schemaValidator();
 var SwaggerUi = require('swagger-tools/middleware/swagger-ui');
 module.exports = app; // for testing

 var config = {
    appRoot: __dirname // required config
  } ;

 SwaggerExpress.create(config, function (err, swaggerExpress) {

 if (err) {
      throw err;
 }

 //install middleware to validate request object
 app.use(validator.requestValidator.bind(validator));
app.use(SwaggerUi(swaggerExpress.runner.swagger));
// install middleware
 swaggerExpress.register(app);

 var middleware = function(req, res , next){
       res.end = function(data , encoding) {
      console.log(data);
 }
  app.use(middleware);
}
 var port = process.env.PORT || 10010;
 app.listen(port);
```

   });

**Comment by theganyo** [comment]
I'm sorry, I don't understand... What are you attempting to accomplish?

**Comment by molokoloco** [comment]
+1 
**"How to get data from response object"**


In my YAML i have :
```
  '/hello':
    x-swagger-router-controller: hello_world
    get:
      description: 
      operationId: hello
      parameters:
        - name: name
          in: query
          description: 
          required: false
          type: string
```
and
```
  '/media/channels/{positionId}':
    x-swagger-router-controller: get_channel
    get:
      description: 
      operationId: getChannel
      parameters:
        - name: positionId
          in: path
          description:
          required: true
          type: integer
          format: int64
```
BUT... After updating to the latest version "req.swagger.params" is empty :-(
In my router :
```
getChannel: function (req, res, next, callback) {
       console.log(req.swagger.params, req.param, req.param('positionId'));
       //> undefined [Function: param] undefined
```

**Comment by molokoloco** [comment]
I have now access to values using "connect" but it brake a lot of code i have made previously using your "express" example :-(

This is really pissing me off . Why do you always change all and introduce breaking changes every time ?
There's not even a working complete exemple :-(
And now there is no more "express" but "connect"... for this package named "apigee-127/swagger-express"
I cannot update and use this anymore , too much alpha....

**Comment by theganyo** [comment]
You've completely lost me. From what you're saying, nobody would be able to run this at all since probably 95% of people run using express. I just tried an fully upgraded project and it works fine, including accessing `req.swagger.params` from inside a controller. If you want an example, you could do the same and that would be a simple one to test. Are you using the [correct npm package](https://www.npmjs.com/package/swagger-express-mw)? What version? The latest is 0.6.0. Can you share a full example or more of your setup? If you provide more information and work with me, perhaps I can help you.

For what it's worth, I have a ton of tests that run for all changes and the engine has about [97% code coverage](https://coveralls.io/github/theganyo/swagger-node-runner). Obviously some issues can and will get though and tests will be added as needed for new scenarios, but I certainly don't feel that your attack on this for "breaking every time" is fair given the amount of time spent on making it a good platform and the number of people that rely on it.

**Comment by theganyo** [comment]
Hey Guys,

I'm not sure if this is your issue, but if you haven't, please be sure you follow the instructions under "upgrading" here: https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.0.

Please let me know if that solves the problem.
Scott

**Comment by axelhodler** [comment]
same issue here, doing the following fixed it:

```yaml
swagger_controllers:
  - onError: json_error_handler
  - cors
  - swagger_params_parser                 # <= Add this line here
  - swagger_security
  - _swagger_validate
  - express_compatibility
  - _router
```
