### ISSUE TITLE
how to "deny" extra elements on request through the schema

### ISSUE THREAD

**Issue by sloncho** [apigee-127/swagger-express#12]
using swagger-express-mw, and having a following yaml:

 ```
 /api/applications:
    x-swagger-router-controller: "applications"
    post:
      operationId: "create"
      consumes:
        - "application/json;"
      produces:
       - "application/json"
      parameters:
      - name: "body"
        in: "body"
        description: "initial application data"
        schema:
          title: NewApp
          type: object
          required:
            - "email"
            - "phoneNumber"
          properties:
            phoneNumber:
              type: "string"
            email:
              type: "string"
```

How do I define that additional elements are not allowed. I.e. I want to prevent posting of:

```
{
   "email":"bla",
   "phoneNumber":"otherbla",
   "dont": {"want":"this to pass validation"}
}
```

In general, I'd like to be able to enforce this for some paths, but not for others.

Cheers
